{"position_name": "python", "position_salary": "8k-13k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                学历必须是统招本科 (二本以上）<br/>有两年的实际开发工作经验\n            "}
{"position_name": "python开发工程师", "position_salary": "9k-14k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                python开发岗位要求：<br/>1、2年以上Python开发经验，两年以上Python服务端开发经验；<br/>2、熟悉MVC框架，熟练掌握Python web开发框架，精通Django或者其他Python web开发框架者优先；<br/>3、具备数据库设计能力，精通掌握MySQL者优先；<br/>4、熟悉Linux/Unix操作系统、常用工具和shell命令，熟悉Apache、Tomcat\\Ngnix等web server的部署和应用<br/>【岗位职责】<br/>1、负责需求开发<br/>2、定位现网问题，并提供解决方案<br/>python自动化测试岗位要求：<br/>1、有系统软件测试经验优先；<br/>2、至少2年以上liunx环境下测试经验；<br/>3、能独立编写python自动化测试脚本或者shell脚本；<br/>4、有公有云经验优先考虑\n            "}
{"position_name": "Python", "position_salary": "8k-12k", "position_label": ["西安 雁塔区 ", "1年以内", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                CIE岗位<br/>掌握常用linux命令，能熟练使用shell脚本。<br/>具备良好的代码能力和学习能力，掌握python/java/ruby等一种或多种语言（python优先）。<br/>有良好的沟通和表达能力（要直接对接多领域人员），工作踏实，主动性好。\n            "}
{"position_name": "python", "position_salary": "8k-12k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                统招二本以上；<br/>一年以上工作经验；<br/>熟悉Python，SQL，spark；<br/>了解机器学习算法。\n            "}
{"position_name": "python自动化", "position_salary": "6k-11k", "position_label": ["西安 长安区 ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1.熟悉python自动化编程；熟悉软件测试相关流程；<br/>2.了解常用自动化框架；<br/>3.了解python自动化框架优先；<br/>4.沟通协调能力好，具备一定的抗压能力，能接受适量的加班\n            "}
{"position_name": "Python", "position_salary": "9k-14k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                工作内容:终端部门新系统开发<br/>要求:熟练使用Python开发语言<br/>       统招二本以上学历，工作经验2年以上\n            "}
{"position_name": "Python", "position_salary": "10k-20k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "软通动力信息技术集团", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                熟悉shell脚本语言，能够熟练编写shell脚本，熟悉linux环境\n            "}
{"position_name": "Python", "position_salary": "8k-15k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "Elight", "company_info": ["批发/零售", "不需要融资", "100-499人"], "position_card": "\n                岗位职责：<br/>1.基于Odoo平台的二次开发及集成第三方平台的工作；<br/>2.主流业务模块开发如销售、采购、库存、财务等模块的开发；<br/>3.熟悉PostgreSQL数据库，能熟练编写SQL语句；<br/>4.接收其他业务部门的需求转化为功能；<br/>5.向其他业务部门提供技术支持。<br/>工作要求：<br/>1.两年以上Python web开发经验，熟练Python编程；<br/>2.熟练使用python库，熟练Python的高效写法；<br/>3.熟练掌握python web框架，如Django，Flask；<br/>4.具备erp项目经验优先；<br/>5.有odoo开发经验优先；<br/>6.有意向在erp方向长期发展。\n            "}
{"position_name": "Python讲师", "position_salary": "6k-7k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                【工作职责】：<br/>1. 根据学员情况，制定学员个性化教案；<br/>2. 按照公司要求，进行“在线1对1 ”授课；<br/>3. 定期汇报备课情况和教学进度，积极反馈学员上课情况。<br/> <br/>【任职要求】：<br/>1. 全日制本科以上学历，计算机相关专业，能力优秀者可适当放宽，985、211院校、国外留学更佳；<br/>2. 熟练运用Python；至少熟悉Python一个应用分支（如web，游戏，爬虫，人工智能）的编程；熟悉pygame模块优先；熟悉HTML、JS、正则表达式、XPath等，有爬虫项目经验优先。<br/>3. 形象气质佳、普通话标准，有责任心，有亲和力，热爱教育事业、喜欢与小朋友沟通，有良好的沟通能力，较强的亲和力。\n            "}
{"position_name": "python讲师", "position_salary": "6k-11k", "position_label": ["西安 雁塔区 唐延路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                【工作职责】：<br/>1. 根据学员情况，制定学员个性化教案；<br/>2. 按照公司要求，进行“在线1对1 ”授课；<br/>3. 定期汇报备课情况和教学进度，积极反馈学员上课情况。<br/> <br/>【任职要求】：<br/>1. 全日制本科以上学历，计算机相关专业，能力优秀者可适当放宽，985、211院校、国外留学更佳；<br/>2. 熟练运用Python；至少熟悉Python一个应用分支（如web，游戏，爬虫，人工智能）的编程；熟悉pygame模块优先；熟悉HTML、JS、正则表达式、XPath等，有爬虫项目经验优先。<br/>3. 形象气质佳、普通话标准，有责任心，有亲和力，热爱教育事业、喜欢与小朋友沟通，有良好的沟通能力，较强的亲和力。\n            "}
{"position_name": "Python", "position_salary": "8k-16k", "position_label": ["西安 雁塔区 ", "经验不限", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                云计算大数据项目组<br/>1年及以上开发经验<br/>2、统招2本以上\n            "}
{"position_name": "python（西安）", "position_salary": "5k-10k", "position_label": ["西安 雁塔区 高新路", "1-3年", "本科"], "company_name": "思特奇", "company_info": ["互联网", "已上市", "1000-9999人"], "position_card": "\n                您的工作内容：<br/>1.进行openstack等IAAS层云计算类产品研发。<br/>2.针对业务的场景进行二次开发。<br/>3.支撑项目关于openstack相关的工程方面方案编写以及一线部署文档的编写。<br/>4.研究开发新版openstack的特性。<br/> <br/>我们对您的要求：<br/>1.国家统招本科，理工类专业优先考虑； <br/>2.具有python开发的相关经验，对云计算类产品有过接触。<br/>3.可以独立自主完成相关项目模块的开发。<br/>4.编写测试以及使用手册。<br/>5.具有open stack相关开发经验优先，具有docker类似的经验优先。<br/> <br/>我们给您的提升：<br/>1、全称参与整个项目周期、不仅局限在某一环节；<br/>2、过程中技术大牛毫无保留的对您各方面的工作指导；<br/>3、主流技术的实践、技术成果的沉淀、知识网面的拓宽等；<br/> <br/>加入我们的理由：<br/>1、一切从薪开始：我们提供具行业竞争力的工资<br/>2、靠谱完善的福利待遇：七险一金+餐补+话补+交通补贴+双休+带薪年假+节日福利等都是小意思<br/>3、不让时间浪费在路上：思特奇位于西安市高新区、紧邻地铁3号线、交通便利、多条公交线路、分分钟抵达公司<br/>4、带你培训带你飞：定期组织外部和内部职业化和管理能力培训（部门内部培训、公司层面培训）、给予个性化的培训资助<br/>5、透明的晋升机制：明确的晋升制度、健全的管理体系、工资和职位的提升机会就在眼前你是否已经对小公司的发展空间感到窒息？<br/>你是否正在为储存已久的能量寻找更为广阔的平台？<br/>别再犹豫了、生命短暂、经不起一份错误的工作、快加入我们吧！\n            "}
{"position_name": "python开发", "position_salary": "9k-17k", "position_label": ["西安 长安区 王寺", "3-5年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                python开发两年以上<br/> <br/>福利：试用期即缴纳五险一金+绩效奖金+节日福利+定期员工活动+节假日+弹性上班时间+加班餐补（交通补助）+十多条班车线路\n            "}
{"position_name": "Python", "position_salary": "10k-15k", "position_label": ["西安 雁塔区 唐延路", "3-5年", "本科"], "company_name": "陕西交通电子", "company_info": ["通信/网络设备", "不需要融资", "500-999人"], "position_card": "\n                职位描述： 负责大数据产品的开发落地； 利用机器学习深度学习等方法进行算法模型设计及实现； 对海量数据进行数据统计，数据挖掘与建模，包括数据工程，模型建立，模型应用及效果评估 职位需求： <br/>1.计算机，数学或相关专业 <br/>2.熟练掌握因子提取、主成分识别、数据降维等数据预处理手段并具有丰富的经验 <br/>3.具有机器学习、深度学习、自然语言处理、分布式计算等算法研究能力，参与或主导过完整的项目开发工作，具有丰富的实战经历<br/>4.精通Hadoop，Storm，Spark，熟练掌握Hbase，Redis，熟练掌握Java，Python开发语言 <br/>5.具备大规模推荐系统的研发经验(推荐算法设计、实现、评估) <br/>6.至少相关工作经验4年以上\n            "}
{"position_name": "Python", "position_salary": "24k-36k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                1  具备3年级以上项目开发经验。<br/>2  熟练掌握Java、python等主流开发语言的一种\n            "}
{"position_name": "python开发", "position_salary": "6k-9k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                熟悉python<br/>熟悉shell及linux<br/>了解服务器<br/>统招二本学历及以上\n            "}
{"position_name": "Python老师", "position_salary": "7k-12k", "position_label": ["西安 雁塔区 唐延路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                工作职责：<br/>1. 根据学员情况，制定学员个性化教案；<br/>2. 按照公司要求，进行“在线 1 对 1 ”授课；<br/>3. 定期汇报备课情况和教学进度，积极反馈学员上课情况。<br/>任职要求<br/>1. 全日制本科以上学历\n            "}
{"position_name": "Python老师", "position_salary": "5k-10k", "position_label": ["西安 雁塔区 科技一路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                工作内容:<br/>给孩子线上一对一教授编程课，<br/>根据具体学员情况调理课程，<br/>定期汇报教学进展，积极反馈学员上课情况<br/>岗位要求:<br/>全日制本科学历及以上<br/>理工科专业，计算机相关专业优先，有学习c语言课程<br/>逻辑思维强，有亲和力<br/>对编程方面比较感兴趣<br/>薪资福利:<br/>周内双休\n            "}
{"position_name": "Python开发", "position_salary": "8k-16k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "中软国际科技服务", "company_info": ["计算机软件", "未融资", "10000人以上"], "position_card": "\n                2. 1-3年以上Python开发经验, 两年以上python服务端开发经验，对数据结构，算法相关知识有一定的见解，有项目开发经验；<br/>3. 熟练掌握Python web开发框架，熟悉Flask、Django等常见框架以及原理，有前端开发经验；<br/>4. 具备关系数据库设计能力，精通掌握MySql者优先；<br/>5. 熟悉Linux平台环境下的开发部署，掌握Linux常用命令，熟悉版本控制工具（Git）优先考虑；\n            "}
{"position_name": "Python开发", "position_salary": "10k-15k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "武汉佰钧成", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                任职资格<br/>1.全职工作2年以上开发经验，有2个以上完整项目的经验；<br/>2.Python基础扎实，熟悉django,flask等常用框架；<br/>3.掌握流行的web框架，至少两年以上的的web开发经验；<br/>4.熟悉常用的工具如Redis，Memcached，Mongodb，Mysql，Nginx等的基本原理和使用；<br/>5.掌握linux环境下的开发和部署；\n            "}
{"position_name": "Python开发", "position_salary": "7k-14k", "position_label": ["西安 长安区 王寺", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                岗位职责：<br/>1、熟悉python web基础框架，如Django等；<br/>2、熟悉Python开发语言；<br/>3、有web安全知识背景；<br/>岗位要求：<br/>1、3年以上工作经验，能够独立开发；<br/>2、统招二本以上相关学历；\n            "}
{"position_name": "Python", "position_salary": "6k-12k", "position_label": ["西安 雁塔区 科技二路", "3-5年", "本科"], "company_name": "西安创成软件信息技术", "company_info": ["计算机软件", "不需要融资", "0-20人"], "position_card": "\n                完成服务端程序代码开发及代码审核、质量控制<br/>对所开发的功能进行测试并建立和完善开发文档<br/>任职要求：<br/>成熟Django框架，继续做后期维护开发<br/>精通Python语言，熟练使用Python标准库和流行的第三方库<br/>熟悉TCP/IP协议及HTTP协议, 了解基本的前端技术，HTML、CSS、JS、Ajax等<br/>熟悉以下主流服务器端开源系统或者其中一部分：Redis/Memcache/Nginx<br/>对代码和设计质量有严格要求，重视Code Review，知道良好的编程习惯的标准。<br/>具备强烈的责任心，对工作有激情，良好的积极主动的沟通能力，良好的团队协作精神，能够承受一定的工作压力。<br/>要求至少2年以上真实工作经验，具有较强的独立解决问题能力。具有团队协作精神，服从公司统一调配管理，维护公司形象与利益，具有良好的职业素养与协作互动能力。<br/>简历可发送*****\n            "}
{"position_name": "Python开发工程师", "position_salary": "8k-16k", "position_label": ["西安 长安区 ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                【岗位需求】急需python开发、自动化/工具开发，工程ci<br/>Python+shell维护，Linux+shell的系统运维<br/>【岗位要求】<br/>二本及以上，1年及以上相关工作经验<br/>有意向欢迎联系我\n            "}
{"position_name": "python双元导师", "position_salary": "10k-15k", "position_label": ["西安 未央区 ", "3-5年", "大专"], "company_name": "传智播客", "company_info": ["在线教育", "已上市", "1000-9999人"], "position_card": "\n                工作职责：1.利用双元模式(配合教学视频讲解)对学生进行教学。<br/>2.解答学生晚自习所遇到问题。<br/>3.运用所掌握知识技巧，提升授课质量。<br/>任职资格：1、熟悉Python开发，了解网络爬虫基本知识；                      <br/>2、熟悉Http/Html/Xpath等<br/>3、熟悉Scrapy或pyspider，有爬虫经验，熟悉爬虫调度策略；<br/>4、有服务器编程经验，熟悉elasticsearch，lucene，hive，redis之中两个，熟悉更多者优先；<br/>5、对新技术知识具有浓厚的学习和研究兴趣，动手能力强，有阅读开源项目源码习惯尤佳；<br/>6、普通话良好，乐于奉献和分享，有上进心；<br/>福利：入职缴纳五险一金+每年晋级调薪机会+各项员工福利+法定节假日\n            "}
{"position_name": "Python", "position_salary": "7k-12k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1、本科及以上学历，计算机、软件工程、信息技术、或其他相关专业毕业；<br/>2、熟悉Python开发流程，有良好的编程思想，有较强的学习能力和团队合作精神；<br/>3. 基础能力强，计算机算法、数据结构较强者优先，对后端性能优化有经验；<br/>4、诚实、踏实、积极主动、抗压能力强，喜欢挑战困难；\n            "}
{"position_name": "python", "position_salary": "10k-20k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                统招二本以上学历<br/>理工科专业<br/>1. 熟练掌握Python的使用，有一定的python web开发经验，熟悉Tornado优先。<br/>2. 至少会使用一种数据库技术，如Oracle、SQL Sever、Mysql、PostgreSQL等。<br/>3. 熟悉Bootstrap、Node.js、.NET、Linux Shell优先。<br/>4. 有良好的编程习惯，沟通能力强，能够独自编写技术文档。<br/>5. 具备较好的学习能力、问题分析能力，可以独立调试解决问题。<br/>6. 良好的沟通协调能力和团队合作意识，工作踏实，态度积极，能够承受工作压力。\n            "}
{"position_name": "Python", "position_salary": "8k-16k", "position_label": ["西安 雁塔区 ", "1-3年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                2年以上系统集成或后台脚本开发经验！<br/>1:具有模块集成开发经验。<br/>2:精通脚本语言（Python.shell）<br/>3:熟练Linux操作系统（基本操作，各类常规服务搭建，系统指标监控和定位手段等）<br/>福利待遇：入职即买五险一金，年底奖金，年终绩效奖金，每月部门聚餐，生日party，带薪年假、产假、陪产假等劳动法规定法定假期都有。<br/>上班时间：周末双休，公司实行一小时弹性工作制，不受每天8小时工作制限制，即每天最晚9:00上班，最早17:30下班，实行每月平均日工时8H ，详细情况以公司考勤制度为准。<br/>中软国际有限公司（以下简称：中软国际）是中国领先的大型综合性软件与信息服务企业，成立于2000年，为香港主板上市公司，股票代码354 。中软国际秉承“奋斗为本，成就客户，创造分享，共同成长”的核心价值观，成为客户长期、稳定、可信赖的合作伙伴，为成为世界级IT服务企业而奋斗！<br/>公司简介：详细请链接官方网站地址http://www.chinasofti.com\n            "}
{"position_name": "Python", "position_salary": "10k-20k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1.本科及以上学历，具有3年及以上Python开发经验；<br/>2.熟练使用Python2和Python3并有实际项目开发经验；<br/>3.有机器学习开发（熟悉Tensorflow/Caffe等来源AI开发框架）经验者优先；<br/>4.具备良好的沟通和理解能力，能承受一定的业务交付压力。\n            "}
{"position_name": "Python", "position_salary": "8k-16k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1、统招本科及以上学历，毕业证学位证齐全，计算机、软件工程相关专业优先，特别优秀的或经验丰富的专业可不限<br/>2、具有良好的逻辑思维和沟通能力，有责任心，积极进取。<br/>3、有意愿加入软通动力集团-华为业务；<br/>4、一年及以上python开发经验，薪资待遇优<br/>6、福利：周末双休，加班调休，缴纳五险一金，节假日福利\n            "}
{"position_name": "Python", "position_salary": "9k-18k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                统招二本以上学历。<br/>有相关工作经验。<br/>开发，自动化。\n            "}
{"position_name": "python双元导师(J11610)", "position_salary": "12k-24k", "position_label": ["西安 未央区 ", "3-5年", "大专"], "company_name": "传智播客", "company_info": ["在线教育", "已上市", "1000-9999人"], "position_card": "\n                工作职责:<br/>1.利用双元模式对学生进行教学。<br/>2.解答学生晚自习所遇到问题。<br/>3.运用所掌握知识技巧，提升授课质量。<br/>任职资格:<br/>年龄26周岁以上，3年以上实际项目经验<br/> 熟练掌握Python基本语法<br/>熟练Flask, Django, 爬虫其中一门技术<br/>普通话标准, 表达流利, 逻辑思维能力强<br/>有人工智能相关工作经验的优先考虑<br/>福利：入职缴纳五险一金+每年晋级调薪机会+各项员工福利+法定节假日\n            "}
{"position_name": "Python开发工程师", "position_salary": "11k-15k", "position_label": ["西安 长安区 ", "1年以内", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1、负责华为云后台的相关开发和维护<br/>2、负责完成设计方案、编码和实现、调试维护等工作<br/>3、全日制211/985优先，三年以上开发经验。能力突出可放宽至两年<br/>4、熟练使用Python、shell、linux开发环境<br/>5、了解网络知识，掌握多线程，数据库等编程知识，有分布式开发经验<br/>6、熟悉JAVA、nginx、lvs优先。\n            "}
{"position_name": "Python高级开发工程师", "position_salary": "20k-40k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                华为云IaaS领域架构师<br/>岗位职责：<br/>1、负责IaaS基础框架、中间件等的模块设计、详细设计、核心模块编写交付等工作。<br/>2、负责IaaS基础框架、中间件等的用例设计、单元测试用例开发，自动化测试用例开发等工作。<br/>3、负责IaaS基础框架、中间件等的关键特性交付管理、线上问题攻关、服务升级变更等工作。<br/>岗位要求：<br/>1、掌握python、java、shell等开发语言；熟悉linux操作系统；掌握基础的数据结构，计算机基础等知识；<br/>2、熟悉云计算业务知识，熟悉OpenStack主要组件的功能和逻辑流程，具备云计算领域一项或多项产品的研发经验；<br/>3、具有虚拟化、分布式软件、海量服务管理、大型软件部署、在线平台升级、系统配置管理的研发和设计经验；<br/>4、熟悉线上大型系统的运维，具备先进的运维理念，有运维系统、运维工具的设计研发经验；<br/>5、具有良好的沟通能力，刻苦、敬业、有上进心，有良好的团队合作精神。对技术有激情，喜欢钻研，能快速接受和掌握新技术，有较强的独立、主动的学习能力；\n            "}
{"position_name": "Python后端工程师", "position_salary": "8k-13k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "四叶草安全", "company_info": ["信息安全", "A轮", "100-499人"], "position_card": "\n                1.本科及以上学历，计算机、软件工程、信息安全、计算机应用等理、工专业；<br/>2.接触了解部分信息安全相关知识如Web安全、漏洞、渗透测试等;<br/>3.3年以上Python开发经验两年以上python服务端开发经验；<br/>4.熟悉MVC架构，熟练掌握Python Web开发框架，精通Flask或者其他Python Web开发框架者优先；<br/>5.具备数据库设计能力，精通掌握MySql者优先；具备Linux环境、数据库、HTTP5 Redis MongoDB等后端开发基础，有RESTful服务构架和应用经验优先;<br/>6.熟悉Linux操作系统，熟悉Apache Ngnix等WebServer的部署和应用；<br/>7.有大型网络服务开发，在高并发，高稳定性方面有经验者优先；<br/>8.具备良好的编码习惯及开发文档书写习惯；<br/>9.具有优秀的团队合作和沟通协作能力，善于学习，乐于分享，能承受较大工作压力\n            "}
{"position_name": "Python开发工程师", "position_salary": "9k-15k", "position_label": ["西安 雁塔区 ", "3-5年", "本科"], "company_name": "润和软件", "company_info": ["移动互联网", "已上市", "1000-9999人"], "position_card": "\n                1.使用Python进行相关的开发工作，配合项目按质按量完成相应的开发任务<br/>2.逻辑思维清晰，能独立完成开发任务并解决遇到的技术问题<br/>3.具有较强的性能优化意识，并发挥积极作用\n            "}
{"position_name": "Python开发工程师", "position_salary": "7k-13k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力信息技术集团", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                1、Python开发基础扎实，有良好的编码习惯；<br/>2、熟悉Python相关开发框架；<br/>3、2年以上相关工作经验，统招二本以上学历。\n            "}
{"position_name": "Python开发工程师", "position_salary": "8k-12k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1. 一年以上的python开发经验，具备python基础能力，熟悉linux，可以进行简单特性开发。<br/>2. 有较强的责任心，能独立承担特性开发<br/>3. 具备较强的沟通能力和团队协作能力。\n            "}
{"position_name": "Python开发工程师", "position_salary": "8k-16k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1. 统招二本以上学历  学信网可查询<br/>2.熟练掌握Python的使用，python或shell开发经验1年及以上。<br/>3. 至少会使用一种数据库技术，如Oracle、SQL Sever、Mysql、PostgreSQL等。<br/>4.弱一点的Python开发经验 ，愿意开发编写自动化用例的也可培养<br/>5.实际工作经验超过三年，可适当放宽学历<br/>6. 有良好的编程习惯，沟通能力强，能够独自编写技术文档。<br/>7. 具备较好的学习能力、问题分析能力，可以独立调试解决问题。8. 良好的沟通协调能力和团队合作意识，工作踏实，态度积极，能够承受工作压力。\n            "}
{"position_name": "Python自动化测试", "position_salary": "9k-13k", "position_label": ["西安 雁塔区 ", "3-5年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                python自动化开发，承担小组长角色。\n            "}
{"position_name": "python开发工程师", "position_salary": "10k-14k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1.计算机相关专业2本以上学历<br/>2.python熟练，linux操作熟练，有openstack经验优先，有设计架构经验<br/>3.招聘骨干人员，良好的发展规划，熟悉django，flask框架，<br/>4.五险一金\n            "}
{"position_name": "python讲师", "position_salary": "8k-12k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "益康特信息科技", "company_info": ["计算机软件", "20-99人"], "position_card": "\n                岗位职责：1.负责Python课程的授课；2、学生答疑，负责帮助学员解决学习过程中的问题；3、负责参与Python课程体系的建设和完善，不断提升业务水平任职要求；4、教学研发工作，主要负责教学大纲、教学PPT、教学案例、教学用书等研发工作<br/>任职资格：1、计算机或相关专业本科及以上学历；2、精通python基础语法，熟练运用python语言；3、拥有扎实的Python编程基础，可以熟练运用Python的常用模块；4、精通Python Web框架（Django/Tornado/Flask); 5、有Python开发的相关经验，曾经担任过培训师或者有意从事培训工作的人员。6、具备优秀的学习能力、创新能力，能够快速掌握新知识；7、责任心强，具有良好的沟通能力，课堂组织能力强，授课生动幽默。\n            "}
{"position_name": "Python开发", "position_salary": "8k-15k", "position_label": ["西安 雁塔区 永松路", "1-3年", "本科"], "company_name": "西安利百家商贸", "company_info": ["互联网", "不需要融资", "500-999人"], "position_card": "\n                统招二本或以上学历，3年以上经验，<br/>1、编程基本功扎实，熟练掌握Python语言，熟练掌握多门开发语言优先<br/>2、熟练掌握算法、数据结构、设计模式，技术涉猎广泛，了解Linux系统<br/>3、有激情、创造力，善于团队协作，有产品意识，热爱产品，对自己开发的产品有认同感<br/>4、热爱程序开发，擅于解决问题，提供个人技术博客，Github优先。\n            "}
{"position_name": "Python讲师", "position_salary": "7k-11k", "position_label": ["西安 雁塔区 高新路", "1年以内", "大专"], "company_name": "西安飞凡软件教育", "company_info": ["在线教育", "未融资", "20-99人"], "position_card": "\n                岗位职责：<br/>1、完成Python学科的授课任务。按照教学大纲、教学进度，高质量地完成日常授课任务；<br/>2、学生答疑，负责帮助学员解决学习过程中的问题，并负责组织和实施学员内部测试；<br/>3、 配合市场部门的招生宣传工作；<br/>4、教学研发工作，主要负责教学大纲、教学PPT、教学案例、教学用书等研发工作；<br/>5、 参加公司组织的内训，不断学习新技术。<br/>任职要求：<br/>1、熟练掌握Python语言，了解Python 3.x新特性，有数据工程领域开发经验；<br/>2、拥有数据分析建模理论、熟悉数据分析建模过程；<br/>3、熟悉基于Python的urllib2、requests等HTTP库，以及lxml、bs4等解析库；<br/>4、熟悉一种Python爬虫框架（Scrapy，PySpider）；<br/>5、熟悉NumPy和SciPy科学计算工具的使用；<br/>6、熟悉Pandas数据分析工具的使用；<br/>7、熟悉Matplotlib和Seaborn等数据可视化工具，了解Bokeh交互式数据可视化者优先；<br/>8、熟悉NLTK、Jieba等文本数据分析工具，以及对数据进行情感分析和分类；<br/>9、了解图像数据处理及分析，以及常用的图像特征描述；<br/>10、了解scikit-learn机器学习工具，以及PCA降维算法原理者优先；<br/>11、了解K-Means（聚类模型）、ARIMA（时序模型）、朴素贝叶斯和人工神经网络（分类和预测模型）：<br/>12、拥有Hadoop开发经验者优先：\n            "}
{"position_name": "软件开发工程师（java、Web、Python、C++、C、C#）", "position_salary": "8k-16k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1、开发语言：java、Web、Python、C++、C、C#，任意一种即可。<br/>2、学历要求：统招二本或以上学历。<br/>3、工作年限要求：1年或以上。<br/>4、Web开发技能要求：用过VUE或angular框架。\n            "}
{"position_name": "讲师（Java、C++、Python）", "position_salary": "8k-12k", "position_label": ["西安 雁塔区 大雁塔", "1-3年", "本科"], "company_name": "小码教育", "company_info": ["在线教育", "C轮", "1000-9999人"], "position_card": "\n                岗位职责：<br/>1.主要负责讲授青少年编程课程；<br/>2．按照公司制定的教学计划，高质量完成教学任务；<br/>3．负责班级日常管理和维护工作；<br/>4．负责学生辅导和教学答疑等工作；<br/>5．参与优化和创新教学课程体系；<br/>6．配合其他部门完成相关工作。<br/> <br/> <br/>任职要求：<br/>1．本科计算机相关专业；<br/>2．具备独立工作能力和学习能力；<br/>3．形象佳，亲和力强，有较强的沟通表达能力；<br/>4．耐心，吃苦耐劳，责任心强，有团队协作能力；<br/>5．有教育培训行业经验者或者相关教师资格证书者优先；<br/>欢迎加入您加入小码王教育！<br/>http://www.xiaoma.wang/\n            "}
{"position_name": "在线python讲师", "position_salary": "4k-6k", "position_label": ["西安 雁塔区 昆明路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                √编程达人  √亲和力满分  √热爱教育  √沟通高手<br/>【职位描述】<br/>l 给孩子教授线上1对1编程课<br/>l 根据学员情况，制定学员个性化教案<br/>l 定期汇报备课情况和教学进度，积极反馈学员上课情况<br/>【岗位要求】<br/>l 全日制专科学历及以上，计算机、理科类专业<br/>l 至少精通一门编程语言，C、C++、Python、JS等等多多益善<br/>（以上面试通过者，本公司提供培训）\n            "}
{"position_name": "Python开发工程师", "position_salary": "8k-16k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "数拓科技", "company_info": ["计算机软件", "B轮", "100-499人"], "position_card": "\n                工作内容：1. 负责平台系统核心业务的架构设计与研发；<br/>2. 根据产品需求，团队讨论分析，给出解决方案，并实现；<br/>3. 对接负责项目，沟通，分享。<br/>任职要求：<br/>1. 热爱编程，强烈渴望学习和应用新技术；独立解决问题的偏执狂加分。<br/>2. 1年以上计算机网络开发相关经验，有python语言背景及linux平台服务器熟练商业项目级别工作经验；<br/>有碾压linux变态潜力性能经验者加分；<br/>3. 熟悉关系数据库及文本类数据库相关开发能力；有开发MongoDB 或 CouchDB插件者加分；<br/>4. 有搜索引擎或大型数据抓取分析的相关工作经验者优先；有高并发交易类项目经验者加分；<br/>5.有大数据挖掘或神经计算网络项目经验者优先；<br/>6. 热爱黑客马拉松或喜欢PK代码性能者，有VIP通道直达。\n            "}
{"position_name": "Python开发工程师", "position_salary": "7k-14k", "position_label": ["西安 雁塔区 旺座现代城", "1-3年", "本科"], "company_name": "世平", "company_info": ["信息安全", "A轮", "100-499人"], "position_card": "\n                任职要求：<br/>1. 2年-3年经验，完成所承担功能模块的开发与单元测试任务；\t\t\t\t\t\t\t\t<br/>2. 完成所承担功能模块与其他模块的集成、部署、修改、重构与调优；\t\t\t\t\t\t\t\t<br/>3. 根据公司的要求编写相关的技术文档：撰写所承担功能模块的设计说明书、开发说明书、测试与部署文档等。\t\t\t\t\t\t\t\t<br/>4. 熟练掌握python语言，有2年使用经验，具备良好的代码风格（PEP-8），掌握常见的数据结构、算法\t\t\t\t\t\t\t\t<br/>5. 熟练使用SVN，熟悉MySql、MongoDB、Redis等Nosql数据库。\t\t\t\t\t\t\t\t<br/>6. 熟悉linux操作系统, 有linux系统软件开发经验；\t\t\t\t\t\t\t\t<br/>7. 对高并发及大数据分析及分析工具了解的优先，对大数据挖掘及挖掘算法了解的优先\t\t<br/>8.熟悉多线程。\t\t\t\t\t\t<br/>9. 对机器学习，深度学习算法了解的优先。\t\t\t\t\t\t\t\t<br/>学历要求<br/>- 计算机及相关专业，本科，技术优秀者，可放宽；<br/>- 2年以上工作经验<br/>- 可阅读英文文档<br/>有团队合作意识，可接受加班及短期出差\n            "}
{"position_name": "Python开发工程师", "position_salary": "9k-18k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "WisdomGarden", "company_info": ["计算机软件", "A轮", "100-499人"], "position_card": "\n                职位描述：<br/>开发和维护公司的教育软件产品，主要基于B/S架构。<br/>我们希望你：<br/>有扎实的编程功底，热爱编程<br/>有python相关技术栈开发经验，虽然在这里你将绝不会只用一种语言和技术编程<br/>热爱且善于学习和钻研各种新技术、新语言<br/>英语水平能够支撑自己及时获取和交流最新的技术信息<br/>有良好的团队合作精神,有责任感,有较好的沟通能力<br/>我们可以提供给你的是：<br/>与国内最有经验的敏捷软件开发团队一起工作的机会，你将有机会采用最先进的技术，实践最极限的敏捷软件开发<br/>结合领先的教育理念和技术，为改善教育行业做贡献\n            "}
{"position_name": "python开发/自动化测试", "position_salary": "9k-14k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                有相关开发/测试3年以上工作经验。<br/>统招二本以上学历，学历证学位证齐全。\n            "}
{"position_name": "python程序员", "position_salary": "5k-10k", "position_label": ["西安 未央区 未央路", "1-3年", "本科"], "company_name": "联创佳讯", "company_info": ["互联网", "未融资", "20-99人"], "position_card": "\n                职位信息 <br/>一、岗位职责：参与搭建公司爬虫技术框架，负责爬取指定目标数据，进行初步数据清洗和统计分析；<br/>二、任职要求：<br/>本科（一本）及以上学历，计算机科学与技术、软件工程、电子信息技术等相关专业优先。并有志在互联网行业发展的。（专科学历，须有2年以上工作经验）<br/>1. 掌握python语言，熟悉常见爬虫开源框架，有爬虫开发工作经验； 熟练使用Django框架，flask框架<br/>2. 熟悉http，html，javascript，css，ajax技术，有开发经验优先；<br/>3. 悉常用数据库mysql，mongodb和redis等和linux系统；<br/>4.熟悉Python网站后台开发。会小程序，公众号开发。\n            "}
{"position_name": "python", "position_salary": "5k-10k", "position_label": ["西安 雁塔区 昆明路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                √编程达人  √亲和力满分  √热爱教育  √沟通高手<br/>【职位描述】<br/>l 给孩子教授线上1对1编程课<br/>l 根据学员情况，制定学员个性化教案<br/>l 定期汇报备课情况和教学进度，积极反馈学员上课情况<br/>【岗位要求】<br/>l 全日制本科学历及以上，计算机、理科类专业<br/>l 至少精通一门编程语言，C、C++、Python、JS等等多多益善<br/>（以上面试通过者，本公司提供培训）\n            "}
{"position_name": "web  angula  vue  js    python", "position_salary": "7k-14k", "position_label": ["西安 雁塔区 ", "1-3年", "本科"], "company_name": "中软国际", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1.精通HTML/css/javascript、jQyery、ajax等。<br/>2.掌握 angular 或Vue或Node.js 更佳。<br/>3.有较好的学习能力和学习主动性。<br/>4.逻辑思维清晰，沟通流畅。<br/>5.有较好的职业素养和团队合作意识。<br/>6.诚恳、务实、能吃苦耐劳。<br/>7本科要求1年以上经验，学信网可查。\n            "}
{"position_name": "Python开发工程师", "position_salary": "8k-16k", "position_label": ["西安 长安区 ", "1-3年", "本科"], "company_name": "软通动力信息技术集团", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                负责大规模文本、图像等数据的抓取、结构化信息的提取、质量识别等工作。<br/>1. 开发分布式网络爬虫<br/>2. 提取结构化信息<br/>3. 识别结构化信息的质量<br/>岗位要求：<br/>1. 熟悉 Linux 开发环境，熟练使用 Shell<br/>2. 熟悉 高并发、高性能分布式系统<br/>3. 熟悉 HTTP协议，熟悉 HTML，JavaScript，XPath<br/>4. 熟悉 网络协议<br/>5. 从事 Python 开发 1年及以上<br/>6. 熟练使用 Python 进行抓取及格式化信息提取<br/>+ python开发\n            "}
{"position_name": "python开发工程师", "position_salary": "12k-20k", "position_label": ["西安  ", "5-10年", "大专"], "company_name": "澳鹏网络", "company_info": ["电子商务", "A轮", "500-999人"], "position_card": "\n                职位描述：<br/>岗位职责：<br/>1、根据实际任务，进行自动化营销，批量营销项目开发，满足市场需求；<br/>2、能独立完成项目开发文档的撰写工作；<br/>3、能够与开发团队中其它成员有效沟通，包括其它工程师、项目经理、产品以及测试，设计出高性能、可扩展而且符合用户需求的方案；<br/>4、对新技术具有较强的研究和解决问题的能力，并能够共享其成果在小组/部门内推广；<br/>5、能够和小组中帮助其它工程师讨论并解决疑难问题；<br/>6、按时保质保量完成产品开发任务；<br/>7、热衷研究新兴技术，对产品进行持续优化。<br/>任职资格：<br/>1、两年以上稳定开发经验，熟悉python语言；<br/>2、熟悉Linux操作，使用git进行版本控制管理，有nginx配置部署经验；<br/>3、熟悉django tornado flask 任一python开发框架，懂代码调试并能持续优化；<br/>4、有mysql.mongodb.redis等常用数据库的使用经验；<br/>5、优良的代码注释习惯，并能编写有条理的开发文档；<br/>6、使用过运维工具，能自行编写简单的SHELL脚本。\n            "}
{"position_name": "Java，web，Python，测试，C++，运维，go", "position_salary": "8k-16k", "position_label": ["西安 长安区 ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                【岗位需求】java开发、Python+shell维护，Linux+shell的系统运维<br/>【岗位要求】<br/>统招二本及以上，1年及以上相关工作经验<br/>有意向欢迎联系我\n            "}
{"position_name": "Python", "position_salary": "5k-8k", "position_label": ["西安 雁塔区 丁白路", "1-3年", "本科"], "company_name": "衡刻", "company_info": ["互联网", "天使轮", "0-20人"], "position_card": "\n                岗位职责：<br/>1.负责公司产品的后端服务开发；<br/>2.优化和搭建后端框架，并不断完善；<br/>3.将需求转化为文档，文档转化为产品，并持续分析。<br/>职位要求：<br/>1.熟练使用Python并掌握至少一门后端语言(python, java, php, ruby, nodejs等)，Flask框架<br/>2.代码质量精益求精，注重性能，并且具备良好的自我管理和自我驱动能力，能够独立完成开发任务。<br/>3.对服务端框架的机制，框架的设计模式，数据库的优化，服务器的负载均衡设计，并发时服务器的优化，服务器的压力测试以及功能模块的单元测试有了解的优先。<br/>4.熟悉在Linux/Mac下的工作环境，熟悉 TCP/UDP/HTTP 等网络协议。<br/>5.熟练使用git进行分支管理、冲突合并。<br/>6.了解MySQL/Redis/MongoDB中至少两种<br/>7. 熟悉JavaScript，了解ES6\n            "}
{"position_name": "Python开发工程师", "position_salary": "8k-16k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1、python开发基础扎实，有良好的编码习惯<br/>2、熟悉python相关开发框架<br/>3、2年以上相关工作经验，统招二本以上学历.\n            "}
{"position_name": "Python自动化测试", "position_salary": "8k-16k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                1.统招二本以上学历<br/>2.两年以上工作经验，熟练Linux操作<br/>3.熟悉Python脚本开发，熟悉测试流程\n            "}
{"position_name": "Python", "position_salary": "9k-14k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "佰钧成", "company_info": ["计算机软件", "不需要融资", "1000-9999人"], "position_card": "\n                做Python工具开发，熟悉Python,\n            "}
{"position_name": "python讲师", "position_salary": "6k-10k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "翰海睿智", "company_info": ["数据服务", "不需要融资", "20-99人"], "position_card": "\n                1. 两年以上 Python 开发经验，熟悉 Python 语言开发；<br/>2. 熟悉 Django/Flask 等 Web 开发框架；<br/>3. 熟悉 BeautifulSoup/Scrapy 爬虫开发的优先；<br/>4. 熟悉 Pandas/NumPy 数据分析的优先；<br/>5. 熟悉 Python 数据可视化的优先；<br/>6. 熟悉 scikit-learn 或参加过 kaggle 竞赛的优先。<br/>7.从事软件培训行业优先。<br/>8.有讲师讲师经验者优先。\n            "}
{"position_name": "C/C++/ java/python", "position_salary": "10k-11k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "华为技术有限公司", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                华为IT产品线研发岗位火热招聘中，工作地点西安，欢迎大家推荐！内转、社招均可。<br/>软件开发/测试岗位要求：<br/>1）全日制大学本科及以上学历，本3硕2。<br/>2）熟悉C/C++/ java/python任一种语言，熟悉Linux/Unix或vxWorks操作系统。<br/>3）具备独立的软件模块设计、开发、测试能力。<br/>联系方式：<br/>电话：*****<br/>邮箱：*****\n            "}
{"position_name": "Python", "position_salary": "10k-20k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                1、熟练掌握C、C++、python等一种及以上编程语言，熟悉嵌入式Linux编程环境，有相关软件开发、测试经验；<br/>2、熟悉ARM、PPC、X86架构和Linux开发经验优先。<br/>3、熟悉测试方案设计和常用黑白盒测试设计方法，具备独立完成过软件测试设计工作能力优先。\n            "}
{"position_name": "Python", "position_salary": "15k-25k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                【招聘】华为技术有限公司西安研究所现招聘一批高素质，高技能，高标准优秀人才，只要您满足以下条件，请不要犹豫，直接发送简历或电话联系我们。<br/>岗位要求：<br/>1、 有志于长期从事通信软件行业，想充分体现人生价值；<br/>2、社招:国家重点院校211/985毕业，有互联网公司开发经验者优先。<br/>3、熟练掌握Python和shell脚本开发。<br/>4、具备良好的团队合作意识和沟通能力。\n            "}
{"position_name": "Python", "position_salary": "6k-12k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "华商传媒二三里", "company_info": ["移动互联网", "A轮", "100-499人"], "position_card": "\n                岗位职责：<br/>1.负责各产品的数据抓取需求；<br/>2.负责开发各种爬虫；<br/>3.负责爬虫核心算法的策略优化研究；<br/>4.参与产品设计开发全流程；<br/>岗位要求：<br/>1、计算机相关专业；<br/>2、熟悉linux，精通Python语言开发，C语言基础扎实，了解常用的python框架 flask、django ，熟悉svn；<br/>3、熟悉tcp/ip,http等常见网络协议；<br/>4、熟悉MySQL数据库，了解NoSQL的优先考虑；<br/>5、熟悉常用的数据结构和算法，熟悉软件开发流程，具备独立开发调试、测试和部署能力；<br/>6、有良好的编码习惯，对自己以及自己的代码要求严格，具备较好的文档创作能力。\n            "}
{"position_name": "Python在线编程教师", "position_salary": "5k-10k", "position_label": ["西安 雁塔区 科技一路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                岗位职责:<br/>1、根据课程设置要求，认真备课，编写教案，管理课程器材，课后总结教学经验；<br/>2、按照公司要求，结合每个学生不同情况进行授课，知道学生搭建机器人及相关编程；<br/>3、积极参与公司定期的教学研讨会，提高自身授课水平；<br/>4、积极主动的与教务沟通学生上课情况，做好课后反馈。<br/>任职要求：<br/>1、全日制本科学历及以上，数学、物理、机械类、计算机类、电气自动化类、师范类相关专业优先；<br/>2、具有行业经验（乐高、森孚、泊思地等）优先；<br/>3、动手能力强，熟悉C语言、Python等；<br/>4、较强的语言表达和沟通能力；<br/>5、热爱教育事业，喜欢与孩子互动，具有爱心和责任心；<br/>6、喜欢探索最新科技产品，创客优先；<br/>7、对机器人教育行业有兴趣，希望长期发展者。<br/>双休+五险一金+带薪年假+十三薪+弹性工时\n            "}
{"position_name": "Python", "position_salary": "5k-9k", "position_label": ["西安 雁塔区 高新路", "1-3年", "本科"], "company_name": "大禹网科", "company_info": ["计算机软件", "未融资", "0-20人"], "position_card": "\n                工作要求：<br/>1. 2年以上相关工作经验；<br/>2. 熟悉python，熟悉django（或 其他python web开发框架）； <br/>3. 了解MVC开发模式；<br/>4.可以进行web前端开发，对HTML/CSS/javascript有 一定了解和使用；<br/>5.具备团队合作精神，积极的工作态度和较强的责任心，良好的沟通和学习能力。<br/>除了这些要求，如果你具备以下条件更优：<br/>1. 有互联网从业背景；<br/>2. 熟悉nginx、redis、mongoDB、mysql等开源软件；<br/>3. 有过大规模性能调优经验；<br/>4.了解常见WE攻击手段和防护技术。\n            "}
{"position_name": "Python讲师", "position_salary": "6k-10k", "position_label": ["西安 雁塔区 交大", "3-5年", "本科"], "company_name": "青柠檬", "company_info": ["互联网", "20-99人"], "position_card": "\n                1.能够按时完成基本教学任务<br/>2.参与教学大纲等教学文档指定<br/>3.安排并辅导学生完成阶段考试和就业<br/>4.有教育培训经验有先\n            "}
{"position_name": "Python", "position_salary": "6k-11k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "微感", "company_info": ["互联网", "不需要融资", "20-99人"], "position_card": "\n                、使用Python进行相关的开发工作，配合项目按质按量完成相应的开发任务<br/>　　　2、熟悉html/css 以及 JavaScript<br/>　　　3、逻辑思维清晰，能独立完成开发任务并解决遇到的技术问题<br/>　　　4、具有较强的性能优化意识，并发挥积极作用<br/>任职要求：<br/>　　1、本科及以上学历， 计算机相关专业优先；<br/>　　2、2年及以上相关工作经验；<br/>　　3、了解Python、Java开发语言；<br/>　　4、有较好的沟通能力与团队协作精神,服从工作安排,遇到问题积极主动沟通；<br/>　　5、综合素质较高,具有较强的逻辑思维能力和良好学习能力；\n            "}
{"position_name": "Python", "position_salary": "10k-20k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "华为技术有限公司", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                华为技术有限公司（西安）无线网管产品现面向全球招聘，<br/>只要您满足以下条件之一，请不要犹豫，拿起电话联系我们。<br/>1、BAT及一线互联网公司，撸的一手好代码。<br/>2、过去3年获得过华为offer，依然奋斗在编码一线。<br/>3、211/985及邮电类院校，工作一到三年，日扣代码三百行。<br/>排他条件：<br/>无编码经验、专升本、有休学经历、四级证/毕业证/学位证不齐全者。<br/>工作地：西安<br/>技能要求：<br/>熟练掌握C＋＋/Java/Python（三选一）语言，熟练掌握Sybase/Oracle/SQL（三选一）数据库脚本开发及性能调优；熟悉Linux操作系统基本操作，具备独立完成需求分析、设计、开发能力。\n            "}
{"position_name": "Python", "position_salary": "20k-40k", "position_label": ["西安  ", "5-10年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                【岗位职责】<br/>1、参与华为公有云自动化云平台建设工作，涉及监控与故障处理系统、发布系统、事件管控、大数据及智能客户支持等领域相关服务代码开发，能够与团队共同高质量交付产品;<br/>2、根据客户需求进行软件的概要设计和详细设计，学习和使用设计模式; <br/>3、完成代码开发、单元测试、系统测试，掌握代码编写技术和测试技术;<br/>4、完成从需求到设计、再到开发和上线等项目周期中端到端的各个环节;<br/>【岗位要求】<br/>专业知识要求：<br/>1、985，211重点院校计算机相关专业，本科及以上学历，英语通过四级及以上;<br/>2、熟练掌握至少以下语言中的一种：C/C++/Java/C#/GO/Python/PHP/Python/Shell等编程语言及脚本语言;<br/>3、熟悉多线程、高并发等开发技术，有独立解决性疑难问题的能力者优先;<br/>4、有云计算、运维产品研发经验优先;\n            "}
{"position_name": "Python", "position_salary": "15k-30k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "深圳华为", "company_info": ["通信/网络设备", "不需要融资", "10000人以上"], "position_card": "\n                华为IT产品线研发岗位火热招聘中，工作地点西安，欢迎投递简历咨询<br/>软件开发/测试岗位要求：<br/>1）全日制大学本科及以上学历，本3硕2。<br/>2）熟悉C/C++/ java/python任一种语言，熟悉Linux/Unix或vxWorks操作系统。<br/>3）具备独立的软件模块设计、开发、测试能力。<br/>联系方式：<br/>电话：*****<br/>邮箱：*****\n            "}
{"position_name": "Python", "position_salary": "15k-30k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                一.工作内容：<br/>负责华为云化产品智能运维平台的设计、开发及关键技术研究。<br/>二.岗位要求：<br/>1、本科及以上学历<br/>2、两年以上互联网软件开发工作经验<br/>2、熟悉java/c＋＋/Python/go之中至少一种开发语言<br/>3、有大型互联网公司工作经验者优先\n            "}
{"position_name": "Python", "position_salary": "15k-30k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "秦贝", "company_info": ["电子商务", "不需要融资", "100-499人"], "position_card": "\n                岗位职责：<br/>编码工作：根据需求实现模型和软件功能，主要编程语言Python<br/>研究工作：根据需要完成课题方向的研究，主要面向数据分析、数据挖掘、机器学习等方向<br/>培训工作：根据需要完成对其他技术人员的培训<br/>任职资格：<br/>1、精通Python初级编程技能（字符处理、函数、类、环境管理、模块、异常处理、数据库调用等）<br/>2、掌握Python中级编程技能（闭包、运算符重载、装饰器、ORM、函数式编程、单元测试、异步编程、并行计算、性能优化策略等）<br/>3、熟悉网络基础知识（HTTP、JSON、XML、爬虫、网络协议等知识）<br/>4、熟悉常用的几种设计模式（单例模式、命令模式、模版模式等）<br/>5、掌握常用的Python数据分析工具（NumPy、Pandas、Matplotlib等）<br/>6、具备基本的数学功底（微积分、线性代数、概率统计）<br/>7、至少两年数据分析经验，本科及以上学历\n            "}
{"position_name": "Python", "position_salary": "18k-20k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "华为技术有限公司", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                华为IT产品线研发岗位火热招聘中，工作地点西安<br/>软件开发/测试岗位要求：<br/>1）全日制大学本科及以上学历<br/>2）熟悉C/C++/ java/python任一种语言，熟悉Linux/Unix或vxWorks操作系统。<br/>3）具备独立的软件模块设计、开发、测试能力。\n            "}
{"position_name": "Python", "position_salary": "10k-20k", "position_label": ["西安  ", "1年以内", "本科"], "company_name": "华为技术有限公司", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                容器应用开发工程师  <br/>1、参与Docker、Kubernetes/Swarm/Mesos等容器相关领域的开源开发工作<br/>2、 参与ICT场景下容器的需求分析、关键特性开发和交付工作<br/>3、探索容器领域的前沿技术<br/>岗位要求：<br/>1、 拥有完整的大中型项目开发经历，3年以上开发经验；<br/>2、 熟悉Docker相关开源技术，有Docker开发经验；<br/>3、 熟悉Kubernetes/Swarm/Mesos等容器编排方案，对底层原理有一定了解；<br/>4、 对虚拟化技术，尤其是网络层面有深入理解，参与过大规模环境部署或优化；<br/>5、 熟悉云计算技术中常见的监控、存储和日志收集等方案。\n            "}
{"position_name": "Python", "position_salary": "8k-15k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "艾润物联", "company_info": ["计算机软件", "天使轮", "100-499人"], "position_card": "\n                岗位职责：<br/>1、参与或负责产品程序设计和开发，能够提供高标准的设计要求方案<br/>2、与产品负责人及组员一起，进行需求分析，整理规划。制定产品改进和优化的可操作性方案<br/>3、能够快速积极解决开发中遇到的技术问题<br/>4、参与公司产品的技术选型和决策<br/>5、通过对产品和技术的优化和快速迭代，满足不断增长的客户需求<br/>任职资格： <br/>1、2-3年以上Python开发经验，基础扎实，对数据结构，算法相关知识有一定的见解<br/>2、本科学历，计算机或电子、自动化相关专业<br/>3、有c/c++开发经验<br/>4、良好的工程素养<br/>能力要求：<br/>1、熟练掌握Python的数据类型、数据结构和常用内置函数，熟悉常见的设计模式<br/>2、熟练掌握网络编程、多进程和多线程(协程加分)<br/>3、熟悉web框架(Flask、Tornado等至少一种)，相关接口协议，有其他编程语言能力(c/c++优先考虑)<br/>4、掌握关系数据库MySQL的相关知识，能完成业务数据表的设计和优化<br/>5、熟悉非关系型数据库(redis)的常用操作和使用场景<br/>6、熟悉Linux平台环境下的开发部署，掌握Linux常用命令，熟悉版本控制工具（Git）<br/>素质要求：<br/>1、良好的沟通能力和团队合作精神<br/>2、具有分享精神和责任感<br/>3、有很强的学习能力，有主动性和上进心\n            "}
{"position_name": "python", "position_salary": "9k-18k", "position_label": ["西安  ", "3-5年", "大专"], "company_name": "艾润物联网", "company_info": ["移动互联网", "天使轮", "100-499人"], "position_card": "\n                岗位职责：<br/>1. 负责产品服务器端程序设计和开发，能够提供高标准的设计要求方案；<br/>2. 与产品负责人及组员一起，进行需求分析，整理规划。制定产品改进和优化的可操作性方案；<br/>3. 能够快速积极解决开发中遇到的技术问题；<br/>4. 目标导向，不断通过产品和技术数据进行改进，并完成快速迭代，满足不断增长的客户需求；<br/>任职要求：<br/>- 2-3年以上Python 后端开发经验，对数据结构，算法相关知识有一定的见解，有大中型项目开发经验；<br/>- 熟悉web框架，相关接口协议，有其他编程语言能力优先考虑；<br/>- 掌握关系数据库及 SQL 相关知识，了解基本的设计和优化原则；<br/>- 良好的编码风格及合理的开发安排能力；<br/>- 具有分享精神，有团队合作精神和责任感；<br/>- 有很强的学习能力，有主动性和上进心；<br/>- 熟悉Linux平台环境下的开发部署，掌握Linux常用命令，熟悉版本控制工具（Git）优先考虑；<br/>- 熟悉并擅长 Django/Tornado/Flask之一，有前端开发经验；\n            "}
{"position_name": "Python，openstack，django", "position_salary": "5k-10k", "position_label": ["西安  ", "经验不限", "学历不限"], "company_name": "四叶草安全", "company_info": ["信息安全", "A轮", "100-499人"], "position_card": "\n                对现有云平台有深入研究<br/>对虚拟化技术有深入的了解<br/>熟悉openstack架构，且可对其进行功能定制<br/>熟悉django开发\n            "}
{"position_name": "python工程师", "position_salary": "6k-12k", "position_label": ["西安 雁塔区 郭杜", "5-10年", "本科"], "company_name": "君舟网络", "company_info": ["互联网", "0-20人"], "position_card": "\n                1、 参与公司安全运营平台开发工作；<br/>2、 实现代码需要能够在大数据量、高并发的场景下有优异的性能和稳定性表现；<br/>3、 能快速满足业务需求、应对大数据所带来的技术挑战；<br/>4、 参与自动化测试脚本开发，系统监控、业务分析功能开发。\n            "}
{"position_name": "高级自动化测试（精通python）", "position_salary": "18k-25k", "position_label": ["西安  ", "5-10年", "本科"], "company_name": "甄一创展", "company_info": ["计算机软件", "不需要融资", "100-499人"], "position_card": "\n                高级自动化测试工程师<br/>职位信息：<br/>1、 开发并维护公司的自动化测试框架（基于Python）<br/>2、 根据业务系统需求编写自动化测试脚本、执行测试，出具报告<br/>3、 维护和优化自动化测试脚本<br/>4、 跟踪缺陷，推动问题及时解决，协助开发定位自动化测试过程中发现的问题<br/>5、 负责性能测试与问题定位<br/>6、 指导团队内部的初级工程师<br/>任职要求：<br/>1、 至少5年及以上的自动化测试开发经验<br/>2、 精通Python，有至少3年及以上的Python开发经验；有基于Python的自动化测试框架开发经验的优先考虑<br/>3、 计算机相关专业，本科及以上学历<br/>4、 优异的沟通能力和需求理解能力<br/>5、 精通自动化测试知识与自动化测试框架知识<br/>6、 精通测试流程、测试规范和测试用例的设计 <br/>7、 熟练使用git或svn版本管理工具\n            "}
{"position_name": "Python", "position_salary": "6k-12k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "远江盛邦", "company_info": ["计算机软件", "不需要融资", "20-99人"], "position_card": "\n                工作职责：<br/>1、 和业务团队一起持续优化升级公司现有的安全产品，并进行规划以及负责后端系统需求分析、模块开发；<br/>2、负责相关文档的编写；<br/>任职要求：<br/>1、计算机相关专业；<br/>2、有Python开发经验，熟悉Pythjavascript:;on常用函数库；<br/>3、熟悉Django, Tornado, Flask或其他web框架中的至少一种；<br/>4、熟悉 SQLAlchemy Python ORM 框架使用；<br/>5、熟悉linux开发环境，熟练使用linux各种命令，以及bash脚本。<br/>6、 具备数据库设计能力，了解数据库优化原理。<br/>7、熟练bootsrap,css,jquery<br/>加分项：<br/>1、熟练redis以及mongodb的使用<br/>2、具有良好的代码书写风格。<br/>3、踏实好学。<br/>五险一金，股票期权, 薪资可以根据自己能力具体谈\n            "}
{"position_name": "Python研发工程师", "position_salary": "9k-12k", "position_label": ["西安  ", "1-3年", "大专"], "company_name": "易讯通", "company_info": ["计算机软件", "A轮", "100-499人"], "position_card": "\n                1.优化openstack企业级产品化<br/>2.根据项目需求实现功能化<br/>3.为产品大规模开发实现调优<br/>任职要求：<br/>1.熟悉openstack企业级产品框架，能根据框架实现产品功能。<br/>2.熟练掌握python语言。<br/>3.熟悉django、tornado框架之一，优先考虑。<br/>4.对openstack中，nova、cinder、ceilometer组件熟悉者优先。\n            "}
{"position_name": "python开发工程师（西安）", "position_salary": "10k-16k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "绿盟科技", "company_info": ["信息安全", "已上市", "1000-9999人"], "position_card": "\n                岗位职责：<br/>1、\t参与公司安全运营平台开发工作；<br/>2、\t实现代码需要能够在大数据量、高并发的场景下有优异的性能和稳定性表现；<br/>3、\t能快速满足业务需求、应对大数据所带来的技术挑战；<br/>4、\t参与自动化测试脚本开发，系统监控、业务分析功能开发。<br/>岗位要求：<br/>1、\t三年以上相关工作经验；<br/>2、\t熟悉python，熟悉django（或其他python web开发框架）； <br/>3、\t了解MVC开发模式；<br/>4、\t可以进行web前端开发，对HTML/CSS/javascript有一定了解和使用；<br/>5、\t具备团队合作精神，积极的工作态度和较强的责任心，良好的沟通和学习能力。<br/>具有以下经验者优先：<br/>1、\t有互联网从业背景；<br/>2、\t熟悉nginx、redis、mongoDB、mysql等开源软件；<br/>3、\t有过大规模性能调优经验；<br/>4、\t熟悉网络安全，了解常见WEB攻击手段和防护技术。\n            "}
{"position_name": "Python", "position_salary": "7k-12k", "position_label": ["西安  ", "1年以内", "本科"], "company_name": "微感", "company_info": ["互联网", "不需要融资", "20-99人"], "position_card": "\n                1.使用Python进行相关的开发工作，配合项目按质按量完成相应的开发任务<br/>2.熟悉html/css 以及 JavaScript<br/>3.逻辑思维清晰，能独立完成开发任务并解决遇到的技术问题<br/>4.具有较强的性能优化意识，并发挥积极作用\n            "}
{"position_name": "Python", "position_salary": "5k-10k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "西安图迹信息科技", "company_info": ["企业服务", "B轮", "100-499人"], "position_card": "\n                工作职责：<br/>1.参与运维项目开发以及架构优化<br/>2.负责运维平台的后端模块开发<br/>3.负责公司项目的系统升级、日常系统维护，及监控，提供IT软硬件方面的服务和支持，保证系统的稳定；<br/>4.根据项目需求, 项目IT产品的安装,调试、软件实施服务；<br/>5.负责公司产品的现场安装调试、应用指导等实施上线工作；<br/>6.设计、开发运维工具或系统实现自动化管理，提升系统性能和稳定性；<br/>7.跟随公司一起成长<br/> <br/>任职要求：<br/>1.熟悉python,一年以上开发经验<br/>2.了解Liunx系统编程，熟练linux平台配置<br/>3.熟悉flask,django其中至少一种框架；<br/>4.熟悉Tomcat、postgres等常见应用配置及优化<br/>5.熟悉web开发技术，如HTML、JQuery、JavaScript，Ajax优先<br/>6.具有高度责任心，较强抗压能力及良好职业道德\n            "}
{"position_name": "Devops开发工程师（Linux/Python/Docker）", "position_salary": "10k-20k", "position_label": ["西安 雁塔区 旺座现代城", "3-5年", "本科"], "company_name": "上海安畅网络", "company_info": ["互联网", "C轮", "100-499人"], "position_card": "\n                工作职责：<br/>1、通过对开源系统进行二次开发，实现公有云平台下的LINUX、WINDOWS、云数据库等各类生产系统的自动化管理、自动化配置、统一监控及日志收集；<br/>2、参与重要客户架构规划设计、性能调优、运行管理以及日常维护，支持和保障各类生产系统的安全、高效、稳定运行。<br/>3、开发和完善云管理平台，实现操作规范化、自动化，提高工作效率。<br/> <br/>任职资格：<br/>1、全日制大学本科及以上学历，计算机或相关专业，至少3年的相关工作经验；<br/>2、深入理解Linux操作系统的体系结构；<br/>3、熟练使用Python、Java、Shell等语言，且对Python精通掌握；<br/>4、熟悉使用工具Go、Jenkins、Git、GitLab、SVN中的任一种或任多种；<br/>5、有Ansible、SaltStack、Puppet、Zabbix、CMDB等自动化运维软件的开发经验；<br/>6、熟悉虚拟化、Docker、K8S等容器技术；<br/>7、熟练配置及优化Nginx、Tomcat、Redis、HaProxy等系统；<br/>8、参与或发布过开源项目，有大型平台开发经验者优先；<br/>9、有技术博客，在开源社群活跃并有积极贡献者优先；<br/>10、实践过持续集成与持续交付，认同DevOps文化，有DevOps相关的经验者优先；\n            "}
{"position_name": "Python 研发工程师", "position_salary": "8k-10k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "北京韦众承志", "company_info": ["智能硬件", "未融资", "20-99人"], "position_card": "\n                工作职责:<br/>1、负责核心后端服务的设计、开发、优化，包括高性能 API 接口、运维平台、后台数据处理等；<br/>2、对产品功能体验提出改进建议，对技术实现进行持续优化改进；<br/>3、负责相关文档的编写与维护；<br/>任职资格:<br/>1、本科及本科以上学历；<br/>2、精通 Python 语言，熟悉 Django, Twisted 等开源框架；<br/>3、熟悉 MySQL, Redis, InfluxDB 等数据库相关操作、设计规范；<br/>4、熟悉消息队列编程模型；<br/>5、熟悉 HTTP, TCP 相关网络协议；<br/>6、熟悉 Git 使用方法、规范；<br/>7、熟悉 Linux 下的服务器端命令操作；<br/>8、有相关 Python 项目经验，熟悉 Java / Go 语言等优先。\n            "}
{"position_name": "全国在线Python少儿老师", "position_salary": "5k-8k", "position_label": ["西安 雁塔区 昆明路", "经验不限", "本科"], "company_name": "傲梦网络科技", "company_info": ["在线教育", "B轮", "500-999人"], "position_card": "\n                【职位描述】<br/>1、给孩子教授线上1对1编程课<br/>2、根据学员情况，制定学员个性化教案<br/>3、定期汇报备课情况和教学进度，积极反馈学员上课情况<br/>【岗位要求】<br/>1、全日制本科学历及以上，计算机、理科类专业<br/>2、至少精通一门编程语言，C、C++、Python、JS等等多多益善<br/>（以上面试通过者，本公司提供培训）\n            "}
{"position_name": "高级 Python 后台开发工程师", "position_salary": "20k-30k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "星垂智能", "company_info": ["计算机软件", "不需要融资", "20-99人"], "position_card": "\n                星垂智能 ZENO 是一家总部在西安的科技创业公司，由连续创业者们创立，创始人们曾在美国，阿联酋等地工作和创业。目前 ZENO 处于影藏模式中，已经获得来自阿联酋，加拿大和新加坡的客户。公司位于西安，并在迪拜设有分公司。<br/>公司提供完善的福利制度和行业内 Top 5% 的薪资。我们期望新同事拥有良好的英文沟通能力，对新技术的敏锐性和对新鲜事物的好奇心。<br/>薪资<br/> - 初级工程师 15k, 中级工程师 20k, 高级工程师 25k 起，可以沟通，保证市场上前 5% 的薪水<br/>- 五险一金以及其他法律规定的员工基础福利<br/>- 每年至少一次的国外旅行或者到其他国家办公室访问机会<br/>- 产假（无论性别）<br/>- 健身房会员<br/>- 其他人性化的福利政策<br/>职位需求<br/>- 熟悉 Python, 三年以上工作经验<br/>- 熟悉数据库知识<br/>- 熟悉 Clean Code, 代码重构等概念并且有实践经验<br/>- 熟悉 Linux 系统下的系统管理(Docker/Process/Build)<br/>- 良好的代码习惯和 GitHub 协作能力<br/>- 基本的英文沟通能力，英文文档写作能力<br/>加分项：统计 /数据分析 /机器学习背景<br/>优先考虑拥有计算机及电子工程的学士或硕士学位的候选者\n            "}
{"position_name": "Python", "position_salary": "10k-15k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "深圳华为", "company_info": ["通信/网络设备", "不需要融资", "10000人以上"], "position_card": "\n                【招人啦！！！】华为技术有限公司（西安）无线网管产品现面向全球招聘，只要您满足以下条件之一，请不要犹豫，拿起电话联系我们。<br/>1、BAT及一线互联网公司，撸的一手好代码。<br/>2、过去3年获得过华为offer，依然奋斗在编码一线。<br/>3、211/985及邮电类院校，本三硕三，日扣代码三百行。<br/>排他条件：<br/>无编码经验、专升本、有休学经历、四级证/毕业证/学位证不齐全者。<br/>开发岗技能要求：熟练掌握C＋＋/Java/Python（三选一）语言，熟练掌握Sybase/Oracle/SQL（三选一）数据库脚本开发及性能调优；熟悉Linux操作系统基本操作，具备独立完成需求分析、设计、开发能力。<br/>测试岗技能要求：熟练掌握常用软件测试工程方法，能够独立完成需求分析/测试用例设计/测试策略和测试计划制定，熟悉Linux操作系统基本操作，具备Java语言开发能力或自动化测试开发维护经验者优先。<br/>满足以上条件，请抓紧联系。我们提供足够吸引的整体收入，高大上的工作环境，完备的培养体系，明晰的发展通道与晋升空间。<br/>简历发送邮箱：*****\n            "}
{"position_name": "测试开发工程师", "position_salary": "25k-35k", "position_label": ["西安  ", "3-5年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                统招本科及以上学历。<br/>有较强代码编写能力，至少熟练应用java\\python\\JavaScript等一种编程语言。有专职测试开发工程师经验，负责过项目的测试工具开发、测试平台搭建维护等效率提升事务。<br/>专业知识要求：<br/>1.掌握基本的测试理论，了解软件工程、敏捷开发等知识；<br/>2.有GIS、3D相关经验者优先\n            "}
{"position_name": "少儿编程老师", "position_salary": "3k-7k", "position_label": ["西安 雁塔区 电视塔", "1-3年", "大专"], "company_name": "腾语科技", "company_info": ["在线教育", "A轮", "20-99人"], "position_card": "\n                要求有计算机编程经验，喜欢教育行业\n            "}
{"position_name": "测试工程师", "position_salary": "10k-20k", "position_label": ["西安  ", "10年以上", "本科"], "company_name": "软通动力", "company_info": ["计算机软件", "已上市", "10000人以上"], "position_card": "\n                具备自动化测试能力，能熟练使用python，bash语言编写自动化测试代码，具备windows/linux下自动化测试编程能力\n            "}
{"position_name": "IT技术支持", "position_salary": "3k-6k", "position_label": ["西安  ", "应届生", "本科"], "company_name": "耐思托管辅导中心", "company_info": ["培训机构", "未融资", "20-99人"], "position_card": "\n                运维工程师所需基础技能：<br/>精通shell/Python/Perl等1至2种编程语言<br/>熟练掌握常用数据结构和算法，并能灵活运用<br/>熟悉网络基础知识<br/>深入理解Linux操作系统<br/>加分技能：<br/>熟悉开源的监控平台工具，比如：Ganglia、Nagios等<br/>熟练掌握Shell脚本熟悉Awk、Sed等基础工具<br/>熟悉分布式计算或者存储系统，比如Hadoop/Hbase/Storm等<br/>熟悉机器学习原理能付诸实践者更佳<br/>熟悉TCP/IP、HTTP等网络协议，精通socket网络编程<br/>软素质要求：<br/>强烈的责任心与主动性，对所负责工作有owner意识，并能自我驱动成长<br/>能承担较大工作压力，有较强独立分析、解决问题的能力<br/>工作中需要胆大心细，具备探索创新精神\n            "}
{"position_name": "Python讲师", "position_salary": "8k-10k", "position_label": ["西安 碑林区 交大", "3-5年", "本科"], "company_name": "西安野马教育", "company_info": ["在线教育", "未融资", "0-20人"], "position_card": "\n                任职资格：<br/>1、性别不限，28岁以上，统招本科及以上学历，专业不限，3年以上相关工作经验,计算机专业优先考虑；<br/>   2、熟练掌握Python语言，了解Python 3.x新特性，有数据工程领域开发经验；<br/>    3、拥有数据分析建模理论、熟悉数据分析建模过程；<br/>    4、熟悉基于Python的urllib2、requests等HTTP库，以及lxml、bs4等解析库；<br/>    5、熟悉一种Python爬虫框架（Scrapy，PySpider）；<br/>    6、熟悉NumPy和SciPy科学计算工具的使用；<br/>    7、熟悉Pandas数据分析工具的使用；<br/>    8、熟悉Matplotlib和Seaborn等数据可视化工具，了解Bokeh交互式数据可视化者优先；<br/>    9、熟悉NLTK、Jieba等文本数据分析工具，以及对数据进行情感分析和分类；<br/>    10、了解图像数据处理及分析，以及常用的图像特征描述；<br/>    11、了解scikit-learn机器学习工具，以及PCA降维算法原理者优先；<br/>    12、了解K-Means（聚类模型）、ARIMA（时序模型）、朴素贝叶斯和人工神经网络（分类和预测模型）：<br/>    13、拥有Hadoop开发经验者优先：<br/>岗位职责：<br/>1、完成Python学科的授课任务。按照教学大纲、教学进度，高质量地完成日常授课任务；<br/>2、学生答疑，负责帮助学员解决学习过程中的问题，并负责组织和实施学员内部测试；\n            "}
{"position_name": "Python/Django开发工程师", "position_salary": "8k-15k", "position_label": ["西安 雁塔区 高新路", "1-3年", "本科"], "company_name": "斯维智能", "company_info": ["智能硬件", "A轮", "0-20人"], "position_card": "\n                ### 职位描述：<br/>1. 参与需求分析，产品设计，功能开发；<br/>2. 负责系统平台的日常维护；<br/>3. 与团队技术交流，共同进步;<br/>4. 云端服务及其接口的研发工作，主要编程语言是 Python。<br/>### 任职要求：<br/>1. 有扎实的编程功底，热爱编程，精通至少一门开发语言，愿意深入学习Python；<br/>2. 熟悉MVC架构，精通Django开发框架者优先；<br/>3. 具备数据库设计能力，精通掌握SQL、Postgres、MySQL者优先；<br/>4. 熟悉Linux操作系统，熟悉Apache/Ngnix等WebServer的部署和应用；<br/>5. 有大型网络服务开发经验者优先；<br/>6. 具备良好的编码习惯及开发文档书写习惯；<br/>7. 具有优秀的团队合作和沟通协作能力，善于学习，乐于分享，能承受较大工作压力；<br/>8. 有一定的web前端技能，了解或熟悉HTML、CSS、Javascript。\n            "}
{"position_name": "Python", "position_salary": "15k-18k", "position_label": ["西安  ", "1年以内", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                华为IT产品线研发岗位火热招聘中，工作地点西安，欢迎大家推荐！内转、社招均可。<br/>软件开发/测试岗位要求：<br/>1）全日制大学本科及以上学历，本3硕2。<br/>2）熟悉C/C++/ java/python任一种语言，熟悉Linux/Unix或vxWorks操作系统。<br/>3）具备独立的软件模块设计、开发、测试能力。<br/>联系方式：<br/>电话：*****<br/>邮箱：*****\n            "}
{"position_name": "软件研发", "position_salary": "5k-10k", "position_label": ["西安  ", "3-5年", "大专"], "company_name": "西安云雀软件有限...", "company_info": ["计算机软件", "未融资", "20-99人"], "position_card": "\n                熟悉Python开发；<br/>熟悉Python下的Web项目开发；<br/>熟悉Python通信类开发；<br/>对网络协议有一定了解；<br/>擅长使用多线程；\n            "}
{"position_name": "软件研发工程师-C#", "position_salary": "10k-20k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "ThoughtWorks", "company_info": ["互联网", "不需要融资", "1000-9999人"], "position_card": "\n                岗位职责<br/>参与系统的需求调研和需求分析<br/>搭建系统开发环境,完成系统框架和核心代码的实现<br/>负责程序性能优化,系统开发测试、部署和集成<br/>负责解决开发过程中的技术问题<br/>岗位要求<br/>具备1年以上Java/ Python/ Ruby/C#/C++等语言开发经验<br/>熟悉OO<br/>熟悉SQL、 NOSQL等主流数据库<br/>有良好的编程习惯,能够书写规范优质的代码<br/>具备良好的团队协作能力\n            "}
{"position_name": "软件研发工程师-java", "position_salary": "10k-20k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "ThoughtWorks", "company_info": ["互联网", "不需要融资", "1000-9999人"], "position_card": "\n                岗位职责<br/>参与系统的需求调研和需求分析<br/>搭建系统开发环境,完成系统框架和核心代码的实现<br/>负责程序性能优化,系统开发测试、部署和集成<br/>负责解决开发过程中的技术问题<br/>岗位要求<br/>具备1年以上Java/ Python/ Ruby/C#/C++等语言开发经验<br/>熟悉OO<br/>熟悉SQL、 NOSQL等主流数据库<br/>有良好的编程习惯,能够书写规范优质的代码<br/>具备良好的团队协作能力\n            "}
{"position_name": "智能风控工程师", "position_salary": "20k-30k", "position_label": ["西安  ", "经验不限", "硕士"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                智能风控服务-实时反欺诈AI模型能力构建。\n            "}
{"position_name": "软件研发工程师-C++", "position_salary": "10k-20k", "position_label": ["西安  ", "1-3年", "本科"], "company_name": "ThoughtWorks", "company_info": ["互联网", "不需要融资", "1000-9999人"], "position_card": "\n                岗位职责<br/>参与系统的需求调研和需求分析<br/>搭建系统开发环境,完成系统框架和核心代码的实现<br/>负责程序性能优化,系统开发测试、部署和集成<br/>负责解决开发过程中的技术问题<br/>岗位要求<br/>具备1年以上Java/ Python/ Ruby/C#/C++等语言开发经验<br/>熟悉OO<br/>熟悉SQL、 NOSQL等主流数据库<br/>有良好的编程习惯,能够书写规范优质的代码<br/>具备良好的团队协作能力\n            "}
{"position_name": "Java", "position_salary": "17k-34k", "position_label": ["西安  ", "经验不限", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                【华为招聘】本四硕三及以上软件开发，熟练掌握Java/Python/C++开发语言，英语四级或以上，工作地：西安（主要） 岗位技能要求：4年及以上Java项目开发经验，有以下相关经验、技能者优先考虑：<br/>1）熟悉布式软件开发经验者；2）熟悉Openstack、WMWare等云操作系统软件；3）有BSS相关领域经验，以及云计算相关领域开发经验和知识背景者；4）有一定通信业务背景，有OSS相关领域经验，有微服务化软件开发经验优者； 5）有DevOps、全功能团队、产品级敏捷研发模式相关经验者；\n            "}
{"position_name": "运维工程师", "position_salary": "10k-20k", "position_label": ["西安 雁塔区 唐延路", "经验不限", "本科"], "company_name": "庖丁科技", "company_info": ["计算机软件", "A轮", "20-99人"], "position_card": "\n                熟练使用 Linux，包括但不限于 Redhat/CentOS/Debian/Ubuntu 等发行版本<br/>熟练使用 Docker, 熟悉 Docker 生态系统<br/>熟练掌握 Bash 的使用，熟悉 Python 加分<br/>熟悉 Nginx, Git, PostgreSQL 的搭建，维护和使用<br/>搭建/使用/研究过持续集成相关的服务\n            "}
{"position_name": "python兼职讲师", "position_salary": "2k-4k", "position_label": ["西安 碑林区 交大", "3-5年", "硕士"], "company_name": "西安野马教育", "company_info": ["在线教育", "未融资", "0-20人"], "position_card": "\n                主要负责教授青少年Python课程。<br/>1.精通Python全栈开发，精通Django等Web框架；<br/>2.有Python网络爬虫相关开发经验优先；<br/>3.有授课经验优先。\n            "}
{"position_name": "大数据&算法开发工程师", "position_salary": "20k-40k", "position_label": ["西安  ", "5-10年", "本科"], "company_name": "华为", "company_info": ["计算机软件", "不需要融资", "10000人以上"], "position_card": "\n                岗位职责：<br/>具备一定的开发能力，熟练使用Java、Python等至少一种语言。熟悉大数据分析技术优先，熟悉机器学习AI建模优先。<br/>岗位要求：<br/>985，211或海外top院校通信，计算机相关专业毕业，工作年限本科5年以上、硕士3年以上，博士工作年限不设限。\n            "}
{"position_name": "Java", "position_salary": "10k-20k", "position_label": ["西安  ", "经验不限", "学历不限"], "company_name": "ThoughtWorks", "company_info": ["互联网", "不需要融资", "1000-9999人"], "position_card": "\n                岗位职责：<br/>•\t参与系统的需求调研和需求分析 ；<br/>•\t搭建系统开发环境，完成系统框架和核心代码的实现；<br/>•\t负责java性能分析软件的开发;<br/>•\t系统开发测试、部署和集成；<br/>•\t负责解决开发过程中的技术问题；<br/>•\t参与代码维护与备份。<br/>我们的要求：<br/>•\t1年以上的java/C#/C++/Ruby/Python等语言开发经验 ；<br/>•\t熟悉OO；<br/>•\t熟悉SQL、NoSQL等主流数据库；<br/>•\t有良好的编程风格，能够书写规范、优质的代码   ；<br/>•\t良好的团队协作能力；<br/>如果你还具备以下技能那就更好了：<br/>•\t喜欢阅读源代码；<br/>•\t热爱阅读各类技术、非技术书籍；<br/>•\t喜欢学习，拥有持续学习的能力，认为学习本身就是一种乐趣；<br/>•\t喜欢开源软件，乐于知识分享；<br/>•\t拥有自我管理能力，自我驱动，做自己的老板。\n            "}
